### ISSUE TITLE
Will not play mp4 or mov

### ISSUE THREAD

**Issue by Nintoad** [marijnkampf/Random-Photo-Screensaver#36]
All mp4 and mov videos just show a blank blue screen. Avi and pictures are working fine. I am using rps 4.5.7 on Windows 8.1 x64.

**Comment by marijnkampf** [comment]
Do mp4 and mov videos play in your Internet Explorer?

**Comment by Nintoad** [comment]
When I start an mp4 or mov with IE it opens it in WMP, but they do play.

**Comment by marijnkampf** [comment]
RPS uses Internet Explorer for it's display, I would first like to determine whether the issue is with RPS, or IE. 

Whilst seeing the blank screen in RPS, can you press F12 and make a note of the path it saves to (shown at the bottom of the screen). 
Open this folder in explorer window ( typically %programdata%\Random Photo Screensaver\data ). 
Right click on the .html file and choose Open with ... > Internet Explorer.

Can you attache the html file to a message and let me know the result on your system?

**Comment by Nintoad** [comment]
When I open the html file in IE it says "Internet Explorer restricted this webpage from running scripts or ActiveX controls." When I click "Allow blocked content" it plays the video.

As for sending you the html file, github messages only support pics but I can email it to the address on your site if you want.

**Comment by marijnkampf** [comment]
Which version of IE is displayed in the RPS settings?

**Comment by Nintoad** [comment]
11.0

**Comment by marijnkampf** [comment]
I'm not sure what the issue could be. MP4 vidoes play on RPS in my Win 8.1 64bit Virtual Machine. Do you have any user restrictions setup on your system or run any virus scanners or other program that could run interference?

**Comment by Nintoad** [comment]
No not really.But I just tinkered around with IE settings some more and turning on software rendering instead of GPU rendering makes it play the videos but they are extremely choppy. I'm thinking maybe RPS does not like my GPU driver. I using Ati Radeon HD 4870 with 13.4 Legacy Beta Driver.

**Comment by marijnkampf** [comment]
From MSDN: GPU rendering relies heavily on the quality of your video drivers. If you encounter problems running Internet Explorer with GPU rendering enabled, you should verify that your video drivers are up to date and that they support hardware accelerated graphics.
