### ISSUE TITLE
add features like jpegsaver has

### ISSUE THREAD

**Issue by mailinglists35** [marijnkampf/Random-Photo-Screensaver#64]
http://www.goat1000.com/jpegsaver.php

**Comment by marijnkampf** [comment]
Please create an issue for each particular feature you would like to see in RPS. The more activity on an issue the more likely I am to implement it. 

In addition 9 out of 10 features listed there are already available in RPS. I have no intention of copying the full feature set of an existing screensaver, you might as well use that one instead of RPS if you are looking for all their features.
